/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2016 (13.0.4001)
    Source Database Engine Edition : Microsoft SQL Server Express Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2016
    Target Database Engine Edition : Microsoft SQL Server Express Edition
    Target Database Engine Type : Standalone SQL Server
*/

USE [master]
GO

/****** Object:  Database [CheckText]    Script Date: 10/21/2017 1:57:03 PM ******/
CREATE DATABASE [CheckText]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CheckText', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\CheckText.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CheckText_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\CheckText_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [CheckText] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CheckText].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CheckText] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CheckText] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CheckText] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CheckText] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CheckText] SET ARITHABORT OFF 
GO

ALTER DATABASE [CheckText] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CheckText] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CheckText] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CheckText] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CheckText] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CheckText] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CheckText] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CheckText] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CheckText] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CheckText] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CheckText] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CheckText] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CheckText] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CheckText] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CheckText] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CheckText] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CheckText] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CheckText] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CheckText] SET  MULTI_USER 
GO

ALTER DATABASE [CheckText] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CheckText] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CheckText] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CheckText] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CheckText] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CheckText] SET QUERY_STORE = OFF
GO

USE [CheckText]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [CheckText] SET  READ_WRITE 
GO

